### ISSUE TITLE
different output pattern

### ISSUE THREAD

**Issue by Shailuc** [studhadoop/Mapside-Join#1]
Hi Thank you for the valuable inputs, I tried running the driver and I am getting output as below

1 50000,A,Anne,Admin
2 Gokul,Admin,50000,B
3 60000,A,Janet,Sales
4 Hari,Admin,50000,C

but I need the sequential output i.e

1 Anne,Admin,50000,A
2 Gokul,Admin,50000,B
3 Janet,Sales,60000,A
4 Hari,Admin,50000,C

could you please help me with this

**Comment by studhadoop** [comment]
Hi 

You can find the same in 
https://github.com/studhadoop/MapSide-Join-In-order

Happy Hadooping
